version: '3.8'

services:
  test-db:
    image: postgres:16
    container_name: predifi-test-db
    restart: "no"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"  # Use different port to avoid conflicts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 1s
      timeout: 5s
      retries: 30
      start_period: 10s
    volumes:
      - test_pgdata:/var/lib/postgresql/data
    networks:
      - test-network

volumes:
  test_pgdata:

networks:
  test-network:
    driver: bridge 